### ISSUE TITLE
Error during searching of some specific queries.

### ISSUE THREAD

**Issue by thakursaurabh1998** [shubhamguptaji/react-reads-app#1]
### Remember It's not necessary that API calls return perfect data. :smiley:

During search queries such as : `linux`,`biography`

The returned JSON data doesn't contain thumbnail data or Authors.

So it's necessary to look into this matter and handle the data which is not perfect :laughing:

Look into it @shubhamguptaji

**Comment by shubhamguptaji** [comment]
ok i'll fix it

**Comment by thakursaurabh1998** [comment]
toh close phle nhi krte😂😂😂😂😂😂
